### ISSUE TITLE
Empty response received from the server while trying to login

### ISSUE THREAD

**Issue by ghost** [valentinmari/APInstagram#1]
No se que ocurre, los datos están bien... he comparado esta clase con otra hecha en Python y parece que las dos funcionan del mismo modo, pero la otra funciona bien.

¿Qué puede ser?

**Comment by vmari** [comment]
Verificaste que la imagen sea jpg y un cuadrado perfecto?

**Comment by vmari** [comment]
Ahí lo solucioné, había muchos errores... Esta probado todo y funcionando... (Y)

**Comment by ghost** [comment]
@valentinmari 

Era un problema con el SSL, si haces la petición con HTTP todo funciona bien, o con el siguiente código:  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

Ahora parece que funciona bien, sube las imagenes pero se ven así:
![877bb06d5948d2e538d209ab786d46f2](https://cloud.githubusercontent.com/assets/11168614/9295056/8eaa046e-4460-11e5-9292-9f9ab98a64a2.png)

Subí una cuadrada, 1000 x 1000, como me dijiste.

**Comment by vmari** [comment]
Con el ultimo commit arregle un par de cosas, fijate si se soluciona lo de la asignacion de imagen, porque a mi tambien me aparecian en null las imagenes...

**Comment by ghost** [comment]
@valentinmari Sí estoy usando el último commit, paso la imagen como parámetro así: $_FILES["fileToUpload"]["name"] o con fopen pero sigue igual.

**Comment by vmari** [comment]
lo que tenes que pasar como parametro es el path de la imagen... $_FILES["fileToUpload"]["name"] tiene el nombre del archivo, no la ubicación. tendrías que usar $_FILES['userfile']['tmp_name'] donde esta guardado el archivo temporalmente. Mas info: http://php.net/manual/es/features.file-upload.post-method.php

Tambien podes usar move_uploaded_file para moverla a un lugar mas accesible y despues subirla.

**Comment by ghost** [comment]
Sí así también he probado, y nada... es muy raro

**Comment by vmari** [comment]
Quizás sea conveniente usar  http://php.net/manual/es/class.curlfile.php en vez de @file 

Que versión de PHP tenés?

**Comment by ghost** [comment]
5.6

**Comment by ghost** [comment]
No hay solución?? es que me urge bastante

**Comment by vmari** [comment]
Ahora mismo estoy probando de diferentes versiones y diferentes cuentas... siempre funciona. La verdad no se que puede ser. Probá en ejecutar desde consola, sin hacer un script en un servidor.

configura tus datos de acceso en test.php

ejecutalo en la terminal >php test.php

Contame como te fue, y si tira error, decime cual es.

**Comment by ghost** [comment]
Lo solucioné anoche con $cfile = curl_file_create($filename); como decías arriba!! muchas gracias.

**Comment by vmari** [comment]
Perfecto! Un saludo
